### ISSUE TITLE
A question ,A problem,A requirement

### ISSUE THREAD

**Issue by GoldenCreeperJ** [Goshenc/Round-2#1]
为viewBing封装了一个抽象类，十分不错。但是没看见你使用它，是存在什么问题吗？

当取关的up不是最后一个时，最后一个up无法打开，且打开前面的up存在错位，再查查看是哪里的问题

请为你的代码实现合理的项目结构，参考文章[Android开发规范：包命名规范](https://blog.csdn.net/ddnosh/article/details/100658274)

**Comment by Goshenc** [comment]
好的哥，不过我明天还要考试，所以要晚点改

**Comment by Goshenc** [comment]
我已经修改好了

**Comment by GoldenCreeperJ** [comment]
基本没问题了
